### ISSUE TITLE
[PATCH] spelling mistakes

### ISSUE THREAD

**Issue by gregoa** [rjbs/Test-Routine#11]
In Debian we are currently applying the following patch to
Test-Routine.
We thought you might be interested in it too.

    Description: spelling mistakes
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-12-03
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libtest-routine-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by rjbs** [comment]
Thanks, applied!
